---
title: "HW 5"
subtitle: "MTH 344-001 Winter 2022"
author: "Randi Bolt"
date: "3/11/2022"
output: pdf_document
---

## 1. Define a function $f:\mathbb{Z}\times\mathbb{Z}\rightarrow\mathbb{Z}$ by $f(x,y)=3x-y.$

### (a) Prove that $f$ is a surjective homomorphism. 

Let's show $f$ is surjective. Take any $y\in\mathbb{Z}$. Then $(0,-y)\in\mathbb{Z}\times\mathbb{Z}$ and $$f(0,-y)=3(0)-(-y)=y.$$

Hence, $f$ is surjective. 

Now let's show $f$ is a homomorphism. 

\begin{equation}\label{1.1}
\begin{split}
f(3(a_1,a_2)-(b_1,b_2)) &= f(3a_1-b_1,3a_2-b_2)\\
&= 3(3a_1-b_1)-(3a_2-b_2)\\
&= 9a_1-3b_1-3a_2+b_2\\
&= 9a_1-3a_2-3b_1+b_2\\
&= 3(3a_1-a_2)-(3b_1-b_2)\\
&= 3f(a_1,a_2)-f(b_1,b_2)
\end{split}
\end{equation}

Therefore $f$ is a homomorphism. 

### (b) Find the kernel of $f$. 

Let $f:\mathbb{Z}\times\mathbb{Z}\rightarrow\mathbb{Z}$ be defined by $f(x,y)=3x-y$.

\begin{equation}\label{1.2}
\begin{split}
\text{f} &= \{(x,y)\in\mathbb{Z}\times\mathbb{Z}|f(x,y)=0\}\\
&= \{(x,y)\in\mathbb{Z}\times\mathbb{Z}|3x-y=0\}\\
&= \{(x,y)\in\mathbb{Z}\times\mathbb{Z}|3x=y\}\\
&= \{...(-2,-6),(-1,3),(0,0),(1,3),(2,6)...\}
\end{split}
\end{equation}

\newpage

## 2. Let G be a group. Recall that the _center_ of G is the set $$C=\{C=\{g\in G|xg=gx\forall x\in G\}.$$ We showed in HW 2 that C is a subgroup of G. Prove that C is a normal subgroup of G. 

Let $g\in G$ and $h\in C$. Then, 

$$ghg^{-1}=g^{-1}hg=g^{-1}gh=h\in C.$$

## 3. Let $G=\{\mathcal{E},(12), (34), (1324), (1423) , (12)(34), (13)(24), (14)(23)\}$. Prove that $H=\{\mathcal{E}, (12)(34)\}$ is a normal subgroup. 

$\underline{\text{Right Cosets}}$

\begin{equation}\label{3.1}
\begin{split}
H\mathcal{E} &= H = \{\mathcal{E}, (12)(34)\}\\
H(12) &= \{\mathcal{E}(12), (12)(34)(12)\} = \{(12),(34)\}\\
H(1324) &= \{\mathcal{E}(1324), (12)(34)(1324)\} = \{(1324),(1423)\}\\
H(13)(24) &= \{\mathcal{E}(13)(24), (12)(34)(13)(24)\} = \{(13)(24), (14)(23)\}
\end{split}
\end{equation}

$\underline{\text{Left Cosets}}$

\begin{equation}\label{3.2}
\begin{split}
\mathcal{E}H &= H = \{\mathcal{E}, (12)(34)\}\\
(12)H &= \{(12)\mathcal{E}, (12)(12)(34)\} = \{(12),(34)\}\\
(1324)H &= \{(1324)\mathcal{E}, (1324)(12)(34)\} = \{(1324),(1423)\}\\
(13)(24)H &= \{(13)(24)\mathcal{E}, (13)(24)(12)(34)\} = \{(13)(24), (14)(23)\}
\end{split}
\end{equation}

Since $aH=Ha\forall a\in G$, H is a normal subgroup of G. $\square$

Note: $\frac{8\text{ elements in G}}{2\text{ elements in H}}=4\text{ cosets}$

## 4. Let $G=\mathbb{Z}_3\times\mathbb{Z}_4$ and let $H=\langle (1,0)\rangle=\{(0,0),(1,0)\}.$

### (a) Explain why H is a normal subgroup of G. 

### (b) List the elements of the quotient group $G/H$.

\begin{equation}\label{4.b}
\begin{split}
H + (0,0) &= \{(0,0),(1,0)\}\\
H + (1,0) &= \{(1,0),(2,0)\}\\
H + (0,1) &= \{(0,1),(1,1)\}\\
H + (1,1) &= \{(1,1),(2,1)\}\\
\end{split}
\end{equation}

### (c) The quotient group $G/H$ is a group of size 4. Is it isomorphic to $\mathbb{Z}_4$ or $\mathbb{Z}_2\times\mathbb{Z}_2$? Justify your answer. 


## 5. Let G be a group and H be a normal subgroup of G. Suppose that for every $a\in G$ there is a positive integer _n_ such that $a^n\in H$. Prove that every element of the quotient group $G/H$ has finite order. 

## 6. Use the Fundamental Homomorphism Theorem to prove that $$(\mathbb{Z}\times)\mathbb{Z}/K\cong\mathbb{Z}$$ where $K=\langle(0,1)\rangle=\{...,(0,-2),(0,-1),(0,0),(0,1),(0,2),(0,3),...\}$






