---
title: "HW 3"
subtitle: "MTH 344-001 Winter 2022"
author: "Randi Bolt"
date: "2/09/2022"
output: pdf_document
---

## 1. Consider the following permutations in $S_8$: 

$$\alpha = (\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 5 & 1& 3& 8 & 2 & 6 & 4 & 7\end{smallmatrix})\quad\quad\beta=(\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 7 & 2 & 1 & 6 & 5 & 3 & 8 & 4\end{smallmatrix}).$$

### (a) Compute $\alpha \circ \beta$ and $\beta^{-1}$

$\alpha \circ \beta=(\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 5 & 7 & 1 & 4 & 2 & 3 & 6 & 8\end{smallmatrix})$

$\beta^{-1}=(\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 3 & 2 & 6 & 8 & 5 & 4 & 1 & 7\end{smallmatrix})$

### (b) Write $\alpha$ as a composition of disjoint cycles. Then show that $\alpha ^3 = \epsilon.$

Permutation: 

$\alpha=(152)(3)(487)(6)$

Show $\alpha ^3 = \epsilon.$.

$\alpha = (\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 5 & 1& 3& 8 & 2 & 6 & 4 & 7\end{smallmatrix})$

$\alpha^2 = (\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 2 & 5 & 3 & 7 & 1 & 6 & 8 & 4\end{smallmatrix})$

$\alpha^3 = (\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\ 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\end{smallmatrix})$

$\Rightarrow \alpha ^3=\epsilon$. 

### (c) Write $\beta$ as a composition of transpositions. Is $\beta$ an even or odd permutation? 

\begin{equation}\label{1c}
\begin{split}
\beta &= (178463)(2)(5)\\
&= (178463)\\
&= (631784)\\
&= (63)(61)(67)(68)(64)
\end{split}
\end{equation}

Since the number of compositions of transpositions of $\beta$ is odd, the permutation $\beta$ is odd.  

## 2. Let G be a group. Prove that the function: $f:G\rightarrow G$ given by $f(x)=x^{-1}$ is a permutation of G.

Define $f:G\rightarrow G$ by $f(x)=x^{-1}$. 

Since a permutation is a bijective we can show that $f(x)$ has an inverse $f^{-1}(x)=\frac{1}{x}$ by, 

$f^{-1}(f(x))=f^{-1}(x^{-1})=f^{-1}(\frac{1}{x})=x$

and 

$f(f^{-1}(x))=f(\frac{1}{x})=(\frac{1}{x})^{-1}=x$

Therefore, since $f(x)$ is bijective then $f:G\rightarrow G$. $\quad\quad\square$

## 3. Let G be a group. Prove G is abelian if and only if the function $f(x)=x^{-1}$ is an isomorphism from G to G. (Note: By #2 we already know that $f$ is a bijection.)


i) G is abelian $\Rightarrow$ $f(x)=x^{-1}$ is an isomorphism from G to G

Take any $a,b\in G$.

Since G is abelian $f(ab)=f(ba)$. 

We showed in 2 that f is bijective, so now we need to show that it is closed under multiplication. 

$f(ab)=(ab)^{-1}=a^{-1}b^{-1}=f(a)f(b)$. 

Therefore, since G is abelian $\Rightarrow$ $f(x)=x^{-1}$ is an isomorphism from G to G. 

ii) $f(x)=x^{-1}$ is an isomorphism from G to G $\Rightarrow$ G is abelian. 

Since $G\cong G$, then there is an isomorphism $f:G\rightarrow G$. 
Take any $a,b\in G$. 

\begin{equation}\label{3ii}
\begin{split}
f(ab) &= f(a)f(b) \quad\quad\text{, since f is an isomorphism}\\
&= a^{-1}b^{-1}\\
&= aa^{-1}b^{-1}a^{-1}\\
&= b^{-1}a^{-1}\\
&= f(b)f(a)\\
&= f(ba)
\end{split}
\end{equation}

$\Rightarrow f(ab)=f(ba)$, meaning f is commutative. 

Since we already prove in 2 that f is bijective, then f is abelian. 

Therefore, since $f(x)=x^{-1}$ is an isomorphism from G to G $\Rightarrow$ G is abelian.


## 4. Let $G_1$ and $G_2$ be groups and let $f:G_1\rightarrow G_2$ be an isomorphism. Prove that if H is a subgroup of $G_1$, then $$f(H)=\{f(h)|h\in H\}$$ is a subgroup of $G_2$. 


### 5. Determine whether each of the following groups of size 4 is isomorphic to $\mathbb{Z}_4$ or $\mathbb{Z}_2\times \mathbb{Z}_2$. (Recall that $D_4=\{1,r,r^2,r^3,s,sr,sr^2,sr^3\}$ is the group of symmetriese of a square, where $r$ denotes a $90^\circ$ rotation clockwise and $s$ denotes a reflection about a vertical axis.)

### (a) $G_1=\{\epsilon, (12), (34), (12)(34)\}\leq S_4$

$G_1$ is cyclic so $G_1\cong \mathbb {Z}_4$.

### (b) $G_2=\{\epsilon, (1234), (13)(24), (1432)\}\leq S_4$

$G_2$ is cyclic so $G_2\cong \mathbb {Z}_4$.

### (c) $G_3=\{1,r,r^2,r^3\}\leq D_4$

Any element of $G_3$ times itself is the identity, so $G_3\cong \mathbb{Z}_2\times \mathbb{Z}_2$.

### (d) $G_4=\{1,s,r^2,sr^2\}\leq D_4$

Any element of $G_4$ times itself is the identity, so $G_4\cong \mathbb{Z}_2\times \mathbb{Z}_2$.

